version: '3'
services:
  mssql-server-linux:
    image: samuelmarks/mssql-server-fts-sqlpackage-linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: intcom@shell,2020
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
volumes:
  mssql-server-linux-data: